### ISSUE TITLE
Implement workflow to release to Docker Hub

### ISSUE THREAD

**Issue by tongpu** [adfinis-sygroup/back8sup#3]
To allow us to control the released versions of this image we should implement a workflow to build and push the image to Docker Hub when a release is tagged.

**Comment by eyenx** [comment]
@hairmare oh well

**Comment by eyenx** [comment]
I'll take a look at it

**Comment by eyenx** [comment]
The thing is we activated automated build for now.

**Comment by tongpu** [comment]
We can also make Docker Hub do the build, I was simply not aware that it's already doing it.

**Comment by eyenx** [comment]
do we have something in place already for docker hub builds?

I would personally prefer a gh action instead of automated builds.

**Comment by hairmare** [comment]
GitHub Actions support docker out of the box so there is no real need for a specific action (as in a repo that contains a Dockerfile used to create an action that will then run docker commands).

It's very easy to set up a simple GitHub Action that runs docker build/push. But then again you also need to setup a Docker hub secret in GitHub. I think autobuilds are more than fine for building master and tags and they are the least hassle to set up.

Maybe we should start adding badges to repos to clarify that images exist:

[![](https://images.microbadger.com/badges/image/adfinissygroup/back8sup.svg)](https://microbadger.com/images/adfinissygroup/back8sup "Get your own image badge on microbadger.com") [![](https://images.microbadger.com/badges/version/adfinissygroup/back8sup.svg)](https://microbadger.com/images/adfinissygroup/back8sup "Get your own version badge on microbadger.com")

If you really want to do this using an action there is an example [here](https://github.com/projectcaluma/caluma-demo/blob/master/.github/workflows/main.yml) which works fine. I think how it's done makes a whole lot of sense, the trade off of using an action incl. the additional complexity it hides vs. just running 3 lines of shell script aren't really worth it IMO.

Please note that this reasoning mainly applies to "generic" Dockerfile based images. In cases where there is nice high-level tooling (ie. go that has goreleaser) I think it's preferable to use that since the action does a lot of work and is broadly adopted.

**Comment by eyenx** [comment]
we keep automated builds for now
